# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "light" # "contrast", "default", "air", "aqua", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-GB"
title                    : "J C W"
title_separator          : "-"
name                     : "Jérémie C. Wenger"
description              : "London. Mostly text."
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : false # true, false (default)
search_full_content      : false # true, false (default)
search_provider          : lunr # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Jérémie C. Wenger"
  avatar           : "/assets/jcw_b&w_cut.jpg"
  bio              : "Mostly text"
  location         : "London"
  email            : "jeremie[dot]wenger[at]gmail[dot]com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebok"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

projects:
  projects:
    - title: "DIY Freud"
      pitch: "Automated therapist on the cheap"
      icon:
      url: "/diy-freud/"
    - title: "CHATBOT"
      pitch:  "Act and dialogue with a conversational agent-actor."
      icon:
      url: "/chatbot/"
    - title: "Ça artificiel"
      pitch: "L'écriture à l'épreuve de la machine"
      icon:
      url: "/ca-artificiel/"
    - title: "Recursus"
      pitch: "Triptych of computational literature composed of WordSquares, Subwords and AIT"
      icon: "fas fa-fw fa-link"
      url: "http://recursus.co/"
    - title: "Explosure"
      pitch: "Oulipian textual complex"
      icon: "fab fa-fw fa-tumblr"
      url: "http://e-x-p-l-o-s-u-r-e.tumblr.com/"
    - title: "Preexplosure"
      pitch: "More material from Explosure"
      icon: "fab fa-fw fa-tumblr"
      url: "http://p-r-e-e-x-p-l-o-s-u-r-e.tumblr.com/"
  other:
    - title: "Google TTS reads foreign texts with an nearly unreasonably accurate accent"
      pitch: "Casual mischief with Google's Text-To-Speech system"
      url: "/google-tts/"
      icon: "fab fa-soundcloud"
    - title: "Pastiches & mélanges"
      pitch: "Génération automatique de textes grâce au deep learning"
      icon:
      url: "/pastiches/"
    - title: "Computational Thoughts"
      pitch: "Reflections & materials from the MA in Computational Arts at Goldsmiths"
      icon: ""
      url: "/computational-thoughts/"
    - title: "Ideas"
      pitch: "Ideas around text and computation submitted for my admission at Goldsmiths"
      icon: ""
      url: "/ideas/"
    - title: "Euclideas"
      pitch: "A study of rhythms in Max/MSP"
      icon: "fas fa-play"
      url: "/euclideas/"
    - title: "Monodrian"
      pitch: "A series of Processing sketches in homage to Mondrian"
      icon: "fas fa-fw fa-link"
      url: "https://www.openprocessing.org/user/101600"
    # - title: "Solids (NSFW)"
    #   pitch: "Plato meets perversion"
    #   icon: ""
    #   url: "/solids/"
    - title: "Situs Vetus"
      pitch: "Words here and there on Tumblr"
      icon: "fab fa-fw fa-tumblr"
      url: "http://s-i-t-u-s.tumblr.com/"
    - title: "Situs Vetus"
      pitch: "Words here and there on Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/situsvetus"
    - title: "Opus"
      pitch: "Its former abode"
      icon: "fab fa-wordpress"
      url: "https://opus.wordpress.com/"
    - title: "Old Old Words"
      pitch: "Old old words of mine"
      icon: "fab fa-wordpress"
      url: "https://jchwenger.wordpress.com/"
    - title: "Map Manifesto"
      pitch: "A poetic reading of underground maps"
      icon: "fab fa-wordpress"
      url: "https://mapmanifesto.wordpress.com/"

# Site Footer
footer:
  links:
    - label: ""
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto: jeremie[dot]wenger[at]gmail[dot]com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: https://twitter.com/hilperic
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: ""
      icon: "fab fa-fw fa-github"
      url: https://github.com/jchwenger
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: https://www.instagram.com/hilperic/
    - label: "SoundCloud"
      icon: "fab fa-fw fa-soundcloud"
      # url: https://soundcloud.com/hilperic
    # - label: "GitLab"
    #   icon: "fab fa-fw fa-gitlab"
    #   # url:
    # - label: "Bitbucket"
    #   icon: "fab fa-fw fa-bitbucket"
    #   # url:

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "<!--more-->"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: texts/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: # true
      share: true
      related: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
